### ISSUE TITLE
No client search ability

### ISSUE THREAD

**Issue by Jeffrey-P-McAteer** [defanor/pancake#1]
I see that config entries of the form "http://google.com/search?q=" may be made and used by typing their shortcuts, but I see no support for search input when selecting a search menu item (type number 7 - see https://tools.ietf.org/html/rfc1436#page-10).

Were there plans to implement this capability? Have I not read the docs enough?

If there are no plans/prior work I will probably implement search by sending everything after a space from a link or URL; for example given:

```
Retrieving gopher://jmcateer.pw:70/
gopher://jmcateer.pw:70/
        -- Welcome, to the WOORLD of YESTERDAY -- 
(srch) Search[0]
 (dir) Hosting a Gopher Server[1]
(text) Other Gopher Servers[2]
(text) Yet Another Blog Rewrite[3]
```
the user could type
```
0 my search query
```
and `my search query` would be sent to the server.

**Comment by defanor** [comment]
Special handling for Gopher search was indeed left out, though it's
still usable with curl (which is used for document retrieval by
default), since curl uses URL query part as a search query for Gopher
(basically replaces "?" with TAB and unescapes the query part), and
pancake handles relative URIs: so it's not "0 SPC my SPC search SPC
query RET", but "0 RET ?my%20search%20query RET" (or
"?my+search+query").

I'm not sure if it would be worth the complication (and potential
command ambiguity) to handle it in the nicer way (the "0 my search
query" one). Shortcuts can be set if one uses Gopher searches
frequently, after all, and they perform URL escaping, while for other
protocols it probably won't make much sense.

**Comment by Jeffrey-P-McAteer** [comment]
I agree complicating the UI is worth avoiding and I like the use of the URL query - I didn't realize that was possible. I just tested and my server didn't get the search string, so I ran netcat to see what was being sent (my server could be incompetent) and I don't see the search string being sent:

![search-test](https://user-images.githubusercontent.com/15269507/52918099-2574cf80-32c1-11e9-989a-46321f56278c.jpg)

Is the tab replacement only done for shortcuts? I'd like to be able to use this feature with arbitrary locations without having to exit, write some config, and return to search.

Edit: nmap -> netcat (my brain is dumb)

**Comment by defanor** [comment]
Possibly that's a difference in curl versions: the replacement happens
here, with curl 7.29.0 and 7.52.1. And it's done in curl, not in
pancake, so it should be the same with shortcuts and without (could also
be tested just with curl directly, not via pancake). Which curl version
is there?

By the way, shortcut reloading doesn't require exiting: the `load
config` command would reload it.

**Comment by Jeffrey-P-McAteer** [comment]
Here's what I have
```
curl 7.63.0 (x86_64-pc-linux-gnu) libcurl/7.63.0 OpenSSL/1.1.1a zlib/1.2.11 libidn2/2.1.0 libpsl/0.20.2 (+libidn2/2.1.0) libssh2/1.8.0 nghttp2/1.35.1
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```
Also good to know about the reloading, but I'd still have to edit a file.

**Comment by Jeffrey-P-McAteer** [comment]
How is `curl` invoked by pancake to do the `?` to `TAB` conversion?

**Comment by defanor** [comment]
> How is `curl` invoked by pancake to do the `?` to `TAB` conversion?

It used to be just `curl <URI>`, no special options. But checking the
curl's gopher.c history
(<https://github.com/curl/curl/commits/master/lib/gopher.c>) now, and
there were some adjustments in the past year, particularly commits
8f3c3cd and 9026083. So, for newer curl versions it should be "%09"
instead of "?" (and it won't be a relative URL anymore).

I'll fix the gopher search shortcuts in the default config, but this
complicates use of Gopher searches without shortcuts.

**Comment by defanor** [comment]
Fixed the defaults.

Still not sure about adding special handling, since even as it is now
the commands can be ambiguous (made so for the sake of brevity). Maybe
something like "<number>:<query>" could be used though, or "gs <number>
<query>".

**Comment by defanor** [comment]
Perhaps the "gs <number> <query>" command would be a better option to
avoid confusion and mixing with generic ones. I'll probably add it
tomorrow, unless a better idea will come up.

**Comment by Jeffrey-P-McAteer** [comment]
Sounds good, thanks so much!

**Comment by defanor** [comment]
No problem, and thanks for reporting the issue.

It's pushed into the master branch now.
